version: "3"
services:
  csvserver:
    container_name: csvserver
    image: infracloudio/csvserver:latest
    ports:
      - 9393:9300
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
         - './inputFile.txt:/csvserver/inputdata'
